.gitignore, docs/products/ground-2-cloud/faq.md, docs/products/ground-2-cloud/index.md
Like it says on the tin. G2C is in desperate need of an F.A.Q.
=> Add Ground2Cloud FAQ

docs/products/ground-2-cloud/faq.md
A few minor changes to the G2C F.A.Q. page:
- Added a summary of security features. This is something that multiple clients have asked about as they put together their own write ups.
- Mentioned that queueing is an upcoming feature. (Previously, it was listed as not available.)
=> G2C FAQ: add security features, tease queueing

docs/products/ground-2-cloud/faq.md
* Adds information about client security warnings to the FAQ
=> Add information about installer security warnings to the FAQ

docs/products/formulas/examples.md, docs/products/formulas/getting-started.md, docs/products/formulas/how-it-works.md
* Added documentation for the `httpRequest` formula step type.
* Added documentation for the `amqpRequest` formula step type.
* Closes #141 
step types.
=> Added documentation for the new httpRequest and amqpRequest formula

docs/products/formulas/faqs.md
* Adding documentation for multipart and file upload/download request steps in formulas.
* Closes #134
=> formula multipart and file upload/download request docs

api-docs/swagger.html
=> fixed swagger error

docs/elements/sageoneuk/sage-one-uk-create-instance.md, docs/elements/sageoneus/sage-one-us-create-instance.md
=> Updated Sage One instance json

docs/hubs/sageaccounting/index.md
Added padding and fixed finance type
=> Fixed finance typo

api-docs/api.js, docs/hubs/sageaccounting/index.md
Fixed error box on all api docs
=> Fixed red error box on all api docs

docs/products/formulas/examples.md
=> adding an explanation of how to use trigger.args

docs/products/formulas/faqs.md
* Documenting that httpRequest file download works the same as elementRequest file downloa
=> adding clarification that httpRequest file download is also base64 encoded

docs/elements/helpscout/index.md
=> Event hash

docs/elements/intacct/api-documentation.md, docs/elements/intacct/authentication.md, docs/elements/intacct/ceql.md, docs/elements/intacct/error-codes.md, docs/elements/intacct/events.md, docs/elements/intacct/index.md, docs/elements/intacct/intacct-create-instance.md, docs/elements/intacct/intacct-endpoint-setup.md, docs/elements/intacct/transformations.md
=> fixed intacct element id

docs/platform/event-management/security.md
* Event Management Security Guide
=> Event Management Security Documentation

docs/elements/actpremium/actpremium-create-instance.md, docs/elements/actpremium/actpremium-endpoint-setup.md, docs/elements/actpremium/api-documentation.md, docs/elements/actpremium/authentication.md, docs/elements/actpremium/ceql.md, docs/elements/actpremium/error-codes.md, docs/elements/actpremium/index.md, docs/elements/actpremium/transformations.md, docs/elements/autopilot/api-documentation.md, docs/elements/autopilot/authentication.md, docs/elements/autopilot/autopilot-create-instance.md, docs/elements/autopilot/autopilot-endpoint-setup.md, docs/elements/autopilot/bulk.md, docs/elements/autopilot/ceql.md, docs/elements/autopilot/error-codes.md, docs/elements/autopilot/events.md, docs/elements/autopilot/index.md, docs/elements/autopilot/transformations.md
Fixed act premium docs and autopilot docs
=> Fixed act premium docs and autopilot docs

docs/elements/googlesheets/googlesheets-endpoint-setup.md
Fixed G Sheets endpoint setup images
=> Fixed G Sheets endpoint setup images

docs/products/element-builder/element-builder-hooks.md, docs/products/element-mapper/getting-started.md, docs/products/formulas/getting-started.md
* New PROTIP for Element Builder, Element Mapper, and Formula pages indicating that function parameters are immutable.
* A couple of typo fixes.
=> Add protip for immutable parameters.

docs/elements/quickbooksonline/quickbooksonline-create-instance.md
* Added quickbooks online quick provision to devportal docs
* Closes #202
=> Added quickbooks online quick provision

docs/elements.md, docs/elements/actessentials/actessentials-create-instance.md, docs/elements/actessentials/actessentials-endpoint-setup.md, docs/elements/actessentials/api-documentation.md, docs/elements/actessentials/authentication.md, docs/elements/actessentials/ceql.md, docs/elements/actessentials/error-codes.md, docs/elements/actessentials/events.md, docs/elements/actessentials/index.md, docs/elements/actessentials/transformations.md
=> Added act essential docs

docs/products/formulas/examples.md
* Additional note for sub-formula variables.
=> Sub formula note

docs/elements.md, docs/elements/actpremiumcrm/actpremiumcrm-create-instance.md, docs/elements/actpremiumcrm/actpremiumcrm-endpoint-setup.md, docs/elements/actpremiumcrm/api-documentation.md, docs/elements/actpremiumcrm/authentication.md, docs/elements/actpremiumcrm/ceql.md, docs/elements/actpremiumcrm/error-codes.md, docs/elements/actpremiumcrm/index.md, docs/elements/actpremiumcrm/transformations.md
* Added Act premium CRM docs
* Closes #205
=> Added Act premium CRM docs

docs/elements/quickbooksonline/events.md, docs/elements/quickbooksonline/quickbooksonline-create-instance.md
* Added `oauth_verifier` to providerData object in instance.json example
=> QuickBooks OAuth Exchange Paramaters

docs/elements/fieldaware/fieldaware-create-instance.md, docs/elements/pardot/events.md, docs/elements/pardot/pardot-create-instance.md
* Added Pardot version to create instance
=> Added Pardot version to create instance

docs/products/formulas/faqs.md
* Added formula execution error docs
=> Added formula execution error docs

docs/products/formulas/getting-started.md
* New documentation for formula libraries.
* Added `config` to the formula Javascript function signature.
=> New Formula library documentation

docs/elements/salesforce-marketing-cloud/api-documentation.md, docs/elements/salesforce-marketing-cloud/authentication.md, docs/elements/salesforce-marketing-cloud/bulk.md, docs/elements/salesforce-marketing-cloud/ceql.md, docs/elements/salesforce-marketing-cloud/error-codes.md, docs/elements/salesforce-marketing-cloud/index.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-create-instance.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-endpoint-setup.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-events.md, docs/elements/salesforce-marketing-cloud/transformations.md
=> Updated SFDCMar element ID

docs/elements/slack/events.md, docs/elements/slack/slack-create-instance.md, docs/hubs/collaboration/api-documentation.md, docs/hubs/collaboration/index.md
=> Added collab hub docs

docs/elements/quickbooksonline/quickbooksonline-create-instance.md
* Added anchor links for QBO auth types
=> Added anchor links for QBO auth types

docs/products/element-mapper/migrate-objects-and-transformations.md
* Added docs on how to migrate transformations and object definitions from one environment to another.
=> Docs on how to migrate transformatinos and object definitions

docs/elements/hubspot-crm/hubspot-crm-create-instance.md, docs/elements/hubspot/hubspot-create-instance.md
* Added api key auth to hubspot
=> Added api key auth to hubspot

docs/products/element-builder/element-builder-hooks.md, docs/products/element-mapper/getting-started.md, docs/products/formulas/getting-started.md
* Added the documentation for the new CE library functions, and got them all in the right places this time.
=> New CE library function documentation

docs/products/ground-2-cloud/faq.md
* Added list of supported versions of QuickBooks to the F.A.Q
=> Add QuickBooks supported listing to FAQ

docs/elements/onedrivebusiness/onedrivebusiness-create-instance.md
* Updated OneDrive for Business (`onedrivebusiness`) documentation to reflect `document.tagging` parameter
=> OneDrive for Business: Updated configuration parameters in create instance

docs/elements/salesforce-documents/salesforce-documents-events.md, docs/elements/salesforce-libraries/salesforce-libraries-events.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-events.md, docs/elements/salesforce-service-cloud/salesforce-service-cloud-events.md, docs/elements/salesforce/salesforce-events.md
* Updated SFDC event docs with `event.objects`
=> Fixed event docs

docs/elements.md, docs/elements/dynamicscrm/additional-information.md, docs/elements/googledrive/additional-information.md, docs/elements/salesforce-marketing-cloud/additional-information.md, docs/elements/salesforce-marketing-cloud/api-documentation.md, docs/elements/salesforce-marketing-cloud/authentication.md, docs/elements/salesforce-marketing-cloud/bulk.md, docs/elements/salesforce-marketing-cloud/ceql.md, docs/elements/salesforce-marketing-cloud/error-codes.md, docs/elements/salesforce-marketing-cloud/index.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-create-instance.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-endpoint-setup.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-events.md, docs/elements/salesforce-marketing-cloud/transformations.md, docs/elements/sharefile/additional-information.md
* Added BETA and additional info to SFDCMarkCloud
* Closes #1000
=> Added BETA and additional info to SFDCMarkCloud

docs/elements/salesforce-marketing-cloud/additional-information.md
=> Fixed element ID

docs/elements/salesforce-documents/salesforce-documents-events.md, docs/elements/salesforce-libraries/salesforce-libraries-events.md, docs/elements/salesforce-marketing-cloud/salesforce-marketing-cloud-events.md, docs/elements/salesforce-service-cloud/salesforce-service-cloud-events.md, docs/elements/salesforce/salesforce-events.md, docs/getstarted/integration-guide.md
=> Integration guide

docs/products/formulas/examples.md
* Making it clearer that values are coming from the steps context in an elementRequestStream step
=> Making it clearer that values are coming from the steps context in an elementRequestStream step

docs/elements/magento/magento-endpoint-setup.md
* added instructions to create a REST Role and authorize users to that role
=> added steps for API User Roles

docs/elements/hubspot-crm/hubspot-crm-create-instance.md
=> Fixed hubspot crm docs

docs/elements/mailchimp/api-documentation.md, docs/elements/mailchimp/authentication.md, docs/elements/mailchimp/bulk.md, docs/elements/mailchimp/ceql.md, docs/elements/mailchimp/error-codes.md, docs/elements/mailchimp/index.md, docs/elements/mailchimp/mailchimp-create-instance.md, docs/elements/mailchimp/mailchimp-endpoint-setup.md, docs/elements/mailchimp/transformations.md
* Updating the element key to the latest MailChimp element
* Closes #277
=> MailChimp v3 updates

docs/elements/slack/slack-create-instance.md
* Updated docs to the include all the default Slack scopes for our element
=> Updated scope for Slack docs

_config.yml, docs/guides/quickstart-guides/cloud-storage-hub-quick-start-guide.md, docs/guides/quickstart-guides/crm-hub-quick-start-guide.md, docs/guides/quickstart-guides/ecommerce-hub-quick-start-guide.md, docs/guides/quickstart-guides/erp-hub-quickstart-guide.md, docs/guides/quickstart-guides/finance-hub-quick-start-guide.md, docs/guides/quickstart-guides/helpdesk-hub-quick-start-guide.md, docs/guides/quickstart-guides/human-capital-hub-quick-start-guide.md, docs/guides/quickstart-guides/marketing-hub-quick-start-guide.md, docs/guides/quickstart-guides/messaging-hub-quick-start-guide.md, docs/guides/quickstart-guides/social-hub-quick-start-guide.md
=> republished hub qs guides

docs/guides/integration-guide/console-tour.md, docs/guides/integration-guide/definitions.md, docs/guides/integration-guide/error-codes.md, docs/guides/integration-guide/first-integration.md, docs/guides/integration-guide/overview.md, docs/guides/integration-guide/setup-organization.md, docs/overview/error-codes.md
* Added standard error code docs
=> Added standard error code docs

docs/guides/formulas/examples.md
=> added docs for sub-formula configs

docs/guides/integration-guide/first-integration.md, docs/overview/first-integration.md
* Removed youtube videos momentarily
=> Removed youtube videos momentarily

docs/guides/integration-guide/first-integration.md
=> Added two additional videos

docs/overview/first-integration.md
* Added videos under overview section
=> Added videos under overview section

docs/guides/integration-guide/definitions.md, docs/guides/integration-guide/setup-organization.md, docs/overview/definitions.md, docs/overview/setup-organization.md
=> Added more youtube videos

docs/elements/dropbox-business/additional-information.md, docs/elements/dropbox-business/api-documentation.md, docs/elements/dropbox-business/authentication.md, docs/elements/dropbox-business/ceql.md, docs/elements/dropbox-business/dropbox-business-create-instance.md, docs/elements/dropbox-business/dropbox-business-endpoint-setup.md, docs/elements/dropbox-business/error-codes.md, docs/elements/dropbox-business/events.md, docs/elements/dropbox-business/index.md, docs/elements/dropbox/additional-information.md, docs/elements/dropbox/api-documentation.md, docs/elements/dropbox/authentication.md, docs/elements/dropbox/ceql.md, docs/elements/dropbox/dropbox-create-instance.md, docs/elements/dropbox/dropbox-endpoint-setup.md, docs/elements/dropbox/error-codes.md, docs/elements/dropbox/events.md, docs/elements/dropbox/index.md
* Added info regarding new dropboxv2 and businessv2 api
* Closes #308
=> Added info regarding new dropboxv2 and businessv2 api

docs/elements/dynamicscrm/events.md
* Added Polling Config Example for Earlier Versions of Dynamics
* Closes #273
=> Added Polling Config Example for Earlier Versions of Dynamics

docs/elements/marketo/bulk.md
* Added bulk limiter documentation for marketo
=> added limiter documentation for marketo

docs/elements/ecwid/ecwid-endpoint-setup.md
* Updated ecwid endpoint setup docs
* Closes #323
=> Updated ecwid endpoint setup docs

docs/guides/cook-books/salesforce-shopify/provision-instances.md
=> Cook books

docs/elements/volusion/additional-information.md
* Adding "Additional Information" section to Volusion to describe the element's pagination
* Closes #341
=> Volusion Pagination Description

docs/elements/sqlserver/additional-information.md
* Renamed faq.md to additional-information
* Updated metadata and title
* Closes #336
=> Changed Microsoft SQL Server FAQ to Additional Information

docs/elements/zohocrm/zohocrm-create-instance.md
* Removed references of NetSuite from Zoho Create Instance page
* Closes #312
=> Zoho Create Instance Typo

docs/elements/bullhorn/tips.md, docs/elements/dropbox-business/tips.md, docs/elements/dropbox/tips.md, docs/elements/dynamicscrm/tips.md, docs/elements/googledrive/tips.md, docs/elements/hubspot-crm/tips.md, docs/elements/hubspot/tips.md, docs/elements/salesforce-marketing-cloud/tips.md, docs/elements/sftp/tips.md, docs/elements/sharefile/tips.md, docs/elements/sqlserver/tips.md, docs/elements/volusion/tips.md, docs/guides/event-management/tips.md
* Updated Additional information to Tips to correspond with future user experience in console 2.0
* Closes #361
=> Changed Additional Information to Tips

docs/elements/twilio/index.md
=> Changed in order to to just To

docs/elements/adobe-sign/adobe-sign-create-instance.md
=> fixed curl example in create instance to be correct

_includes/polling_and_webhooks_defined.md
* Added a note to the Events section of the Hubspot CRM Element.
*
=> Updated Events pages with a note about raw data

_includes/netsuite/searchtip.md, docs/elements/netsuite-2016-crm/tips.md, docs/elements/netsuite-2016-erp/tips.md, docs/elements/netsuite-2016-finance/tips.md
…content is in an include
* Closes #1000
=> added tips for latest Netsuite elements re search

docs/elements/facebook/facebook-endpoint-setup.md, docs/elements/facebookleadads/facebookleadads-endpoint-setup.md
* Updated Facebook endpoint setup to match FB Lead Ads, minus the Lead Ads-specific info
* Updated FB lead ads for clarity and fixed a typo
=> Updated facebook enpoint setup and made some minor tweaks to FB Lead Ads

docs/elements/zuora/bulk.md
* For https://github.com/cloud-elements/soba/pull/5053
* Added bulk section to Zuora docs
=> Added bulk to Zuora

docs/elements.md
=> fixed broken image and link

_includes/error-codes.md
* Removed error indicators in the code sample and fixed the table so error descriptions are left aligned
=> Fixed issues with Error Codes section

docs/elements/docusign/docusign-endpoint-setup.md
* Need a Developer demo account. Note added to endpoint setup.
* Closes #322
=> Added note to Docusign endpoint setup

docs/guides/element-builder/element-builder-hooks.md, docs/guides/element-mapper/getting-started.md, docs/guides/formulas/getting-started.md
* New documentation for the JS `CE.decode64()` function.
=> Add docs for the decode64 JS library function.

docs/elements/brighttalk/index.md, docs/elements/brighttalk/transformations.md
* Fixed link from overview to create instance
* Fixed BrightTalk API docs
=> Fixed swagger docs and link from overview to create instance

_config.yml
* Updated the algolia config file to include the highlighting and snippeting settings
=> updated algolia configuration file

README.md
updated the read me installation link
=> updated readme installation git URL link

docs/overview/definitions.md
* Added Discovery Service definition to the definition section under overview
* I pulled the definition directly from Jim's definition pdf
=> added discovery api to definitions

docs/elements/quickbooksenterprise/tips.md
Added Quickbooks enterprise tips per story 452. Reviewed by Dave and Cassie.
=> Quickbooks Enterprise Tips

docs/overview/definitions.md
=> Fixed typo in definitions

docs/elements/paypal/api-documentation.md, docs/elements/paypal/authentication.md, docs/elements/paypal/ceql.md, docs/elements/paypal/error-codes.md, docs/elements/paypal/events.md, docs/elements/paypal/index.md, docs/elements/paypal/paypal-create-instance.md, docs/elements/paypal/paypal-endpoint-setup.md, docs/elements/quickbase/api-documentation.md, docs/elements/quickbase/authentication.md, docs/elements/quickbase/bulk.md, docs/elements/quickbase/ceql.md, docs/elements/quickbase/error-codes.md, docs/elements/quickbase/events.md, docs/elements/quickbase/index.md, docs/elements/quickbase/quickbase-create-instance.md, docs/elements/quickbase/quickbase-endpoint-setup.md, docs/elements/quickbase/transformations.md
* updated paypal docs to correct layout
* added swagger docs to the docs for quickbase
=> updated paypal layout and added swagger docs to quickbase docs

docs/elements/hubspot/tips.md
Added Tips for HubSpot Marketing per DevPortal Story 362
=> HubSpot Marketing Tips

docs/elements/concur/tips.md
Added tip/limitation for concur. Did not add for Stripe. See comment in
story.
=> Added tip for Concur

docs/elements/quickbooksonline/tips.md
Added Tips for QuickBooks Online per DevPortal Story per story 595.
=> QuickBooks Online Tips

docs/elements/jira/tips.md
=> Added Jira Tip- 636

docs/elements/brighttalk/api-documentation.md, docs/elements/brighttalk/brighttalk-create-instance.md, docs/elements/brighttalk/bulk.md, docs/elements/brighttalk/ceql.md, docs/elements/brighttalk/error-codes.md, docs/elements/brighttalk/index.md, docs/elements/brighttalk/transformations.md, docs/elements/oraclesalescloud/events.md, docs/elements/salescloud/api-documentation.md, docs/elements/salescloud/authentication.md, docs/elements/salescloud/bulk.md, docs/elements/salescloud/ceql.md, docs/elements/salescloud/error-codes.md, docs/elements/salescloud/index.md, docs/elements/salescloud/salescloud-create-instance.md, docs/elements/salescloud/transformations.md, docs/elements/servicemax/events.md, docs/elements/zuora/api-documentation.md, docs/elements/zuora/authentication.md, docs/elements/zuora/bulk.md, docs/elements/zuora/ceql.md, docs/elements/zuora/error-codes.md, docs/elements/zuora/events.md, docs/elements/zuora/index.md, docs/elements/zuora/transformations.md, docs/elements/zuora/zuora-create-instance.md
* Removed all references to old layout style
=> scanned all files for any references to old layout

assets/js/filter.js, docs/hidden.json, docs/sitemap.html
* Added hidden.json file
* Adding elements to the hidden.json file will now dyncamically hide elements
* Hid the three sage elements, as well as the sage account hub
=> added ability to hide elements dynamically, and hid sage elements

docs/elements/shopify/tips.md
=> Element Tips Shopify

docs/elements/zendesk/tips.md
=> Element Tips Zendesk

docs/elements/eloqua/tips.md
=> Element Tips Eloqua

docs/elements/postgresql/postgresql-create-instance.md
* Updated Postgresql element create instance to include schema name config
=> Updated Postgresql element create instance to include schema name config

_includes/Elements/Hubspot/Tips.md, docs/elements/hubspot-crm/tips.md, docs/elements/hubspot/tips.md
Include Hubspot tips for Hubspot CRM #670
=> Element Tips Hubspot CRM

docs/elements/stripe/stripe-create-instance.md
* Updated stripe Create Instance Page
* Included new configuration settings
=> changed stripe docs to match new provision configuration

docs/elements/concur/concur-create-instance.md, docs/elements/concur/events.md
* Updated create instance file
* Updated Events file
* Closes #867
=> Updated Concur authentication for OAuth2

docs/elements/sageone/events.md, elementTemplate/authenticate.md, elementTemplate/events.md
* Updated events
* Updated authentication
=> Tidied up authentication and events

elementTemplate/authenticate.md, elementTemplate/index.md
=> Changed Base URL section in overview to Custom and not basic

docs/elements/dynamicscrm/dynamicscrm-endpoint-setup.md, docs/elements/dynamicscrm/index.md
* Updated Dynamics CRM with new overview page
* Added version information
* Closes #842
=> Updated Dynamics CRM overview

docs/elements/quickbooksonline/ceql.md
* Update QBO CEQL docs to use template
* Closes #713
=> Update QBO CEQL docs to use template

_includes/Elements/Connectwise/Tips.md, _includes/Elements/WooCommerce/Tips.md, docs/elements/connectwise-helpdesk/tips.md, docs/elements/googledrive/tips.md, docs/elements/woocommerce-rest/tips.md, docs/elements/woocommerce/tips.md, docs/elements/zohocrm/tips.md
Added WooCommerce Tips, Zoho CRM Tips, ConnectWise Tips, GoogleDrive Tips
* Closes #925
=> Adding Kelseys tips while going around the sapc4c image issue

docs/elements/pardot/pardot-create-instance.md
* Added 3 & 4 as Pardot version options
* Fixed response payload example for `POST /instances`
* Closes #932
=> Pardot Instance creation

docs/elements/eloqua/eloqua-endpoint-setup.md, docs/elements/eloqua/events.md, docs/elements/eloqua/index.md, docs/elements/eloqua/tips.md, docs/guides/element-loader/supported-services.md
=> Picking up some leftover Eloquas that should be Oracle Eloquas

docs/guides/formulas/forumulaSteps.md
=> Fix missing comma

docs/guides/formulas/formulaScopes.md
=> removing jjwyse.ngrok.io from docs

docs/guides/account-user-mgmt/index.md, docs/guides/common-resources/index.md, docs/guides/formulasC2/index.md, docs/guides/ground-2-cloud/faq.md, docs/legacy/element-mapper/advanced.md, docs/legacy/element-mapper/api-documentation.md, docs/legacy/element-mapper/definitions.md, docs/legacy/element-mapper/faqs.md, docs/legacy/element-mapper/get-started.md, docs/legacy/element-mapper/index.md, docs/legacy/element-mapper/javascript.md, docs/legacy/element-mapper/migrate-objects-and-transformations.md, docs/legacy/formulas/api-documentation.md, docs/legacy/formulas/definitions.md, docs/legacy/formulas/examples.md, docs/legacy/formulas/faqs.md, docs/legacy/formulas/firstFormula.md, docs/legacy/formulas/formulaScopes.md, docs/legacy/formulas/forumulaSteps.md, docs/legacy/formulas/index.md, docs/legacy/formulas/use-cases.md, docs/platform-api/accounts/account-management.md, docs/platform-api/users/index.md
* Moved old guides to legacy folder
* Added links between old and new
* Updated layout of old guides
=> Moving duplicate guides to legacy

docs/elements/campaignmonitor/ceql.md
* Fixed a typo in the CEQL section
=> fixed typo

docs/elements/shopify/authenticate.md, docs/elements/shopify/bulk.md, docs/elements/shopify/events.md, docs/elements/shopify/setup.md, docs/elements/woocommerce-rest/events.md, elementTemplate/authenticate.md, elementTemplate/bulk.md, elementTemplate/events-polling.md, elementTemplate/events-webhooks.md
* Completed Shopify Events and Bulk
* Fixed an image in WooCommerce REST
* Iterated on the template
* Closes #796, #770
=> Shopify events and bulk

docs/elements/quickbooksenterprise/reports.md
* Updated query parameters for the reports endpoint
* ReportPeriodStart and ReportPeriodEnd
=> updated reports documentation to have correct date query parameters

docs/elements/twitter/events.md
=> Updated examples so they were more clearly examples

docs/elements/dynamicscrm/index.md
=> Updated supported versions for 617

docs/elements/shopify/bulk.md
=> added header back into bulk file

_includes/nav.html
* Updated the search bar to close when a link is clicked or someone clicks outside the search results
=> added listener to close search on click

.vale, docs/guides/elements/auth.md, docs/guides/elements/config.md, docs/guides/elements/custom-elements.md, docs/guides/elements/define-info.md, docs/guides/elements/events.md, docs/guides/elements/hooks.md, docs/guides/elements/index.md, docs/guides/elements/instances.md, docs/guides/elements/resources.md, valeStyles/CE/Avoid.yml, valeStyles/CE/FrequentErrors.yml, valeStyles/CE/Numbers.yml, valeStyles/CE/SentenceLength.yml, valeStyles/CE/SwapTerms.yml, valeStyles/CE/hubs.yml, valeStyles/CE/properCasing.yml, valeStyles/CE/thatsjustwrong.yml, valeStyles/write-good/TooWordy.yml
=> Ran vale and made updates

docs/elements/quickbooksonline/authenticate.md, docs/guides/elements/api-documentation.md, docs/guides/elements/auth.md, docs/guides/elements/hooks.md, docs/legacy/element-builder/create-database-element.md, docs/legacy/element-builder/create-via-api.md, docs/legacy/element-builder/create-via-element-builder-ui.md, docs/legacy/element-builder/element-builder-api-debugging.md, docs/legacy/element-builder/element-builder-authorization-types.md, docs/legacy/element-builder/element-builder-hooks.md, docs/legacy/element-builder/enhance-existing-elements.md, docs/legacy/element-builder/index.md, docs/legacy/element-builder/tips.md
=> Fixed typo in QB online, added TOC to hooks, added API docs section

docs/elements/linkedin/events.md
=> add new polling resource

docs/guides/ground-2-cloud/index.md, docs/guides/ground-2-cloud/who-is-this-for.md
* corrected typo about sections in overview
* added a link to npm for people who don't know what npm is (😱 )
* Closes #1261
=> Fixed Ground2Cloud typo and added link to npm docs

docs/quickstart/integrate.md
=> Fixed some typos

docs/elements/quickbooksenterprise/setup.md
fixed yaml in the QB enterprise setup file
=> Trying to fix a broken build

_posts/2017-10-23-ReleaseNotes-2.138.md
=> Added note to the 2.138 page

_layouts/sidebarapidocs.html
=> removed liquid reference to overview

docs/elements.md
Link is broken in published dev portal.
=> added a slash at the end of the sfmc link

docs/guides/elements/config.md
=> updated the table

docs/guides/index.md
Found an errant slash which is probably the problem
=> Guides link fix

docs/elements/autotask-finance/tips.md
* Closes [DE294](https://rally1.rallydev.com/#/144351344360ud/detail/defect/166183041268)
=> Added tip to autotask finance

_posts/2017-11-27-ReleaseNotes-2.141.md
* Closes [US3250](https://rally1.rallydev.com/#/144351344360d/detail/userstory/176216382012)
=> Added latest release notes

docs/elements/servicenow-oauth/authenticate.md, docs/elements/servicenow-oauth/setup.md
* Closes [DE455](https://rally1.rallydev.com/#/144351344360d/detail/defect/174460350012)
=> Updated ServiceNow Docs

_includes/Elements/Hubspot/Tips.md, _includes/Elements/Hubspot/authenticate.md, docs/elements/hubspot-crm/authenticate.md, docs/elements/hubspot/authenticate.md
* Closes [DE41](https://rally1.rallydev.com/#/144351344360d/detail/defect/152427893512)
=> Updated authenticate and tips with more info about scopes

_posts/2017-11-27-ReleaseNotes-2.141.md
=> fixed formatting in release notes

docs/elements/revel/tips.md
* Closes [US3011](https://rally1.rallydev.com/#/144351344360d/detail/userstory/173246976488)
=> added tip to Revel docs

_posts/2017-09-19-ReleaseNotes-title.md, _posts/2017-09-25-ReleaseNotes-title.md, _posts/2017-10-10-ReleaseNotes-title.md, _posts/2017-10-16-ReleaseNotes-2.137.md, _posts/2017-10-23-ReleaseNotes-2.138.md, _posts/2017-11-11-ReleaseNotes-2.139.md, _posts/2017-11-20-ReleaseNotes-2.140.md
* Closes [DE487](Documentation search showing 'Undefined' for Release notes)
=> Added heading to Release NOtes template

docs/elements/servicenow-oauth/authenticate.md, docs/elements/servicenow/authenticate.md
* Closes [US3437](https://rally1.rallydev.com/#/144351344360d/detail/userstory/178181917948)
=> Updated both ServiceNow elements

_posts/2017-12-04-ReleaseNotes-2.142.md, docs/elements/quickbooksonline/authenticate.md, docs/elements/quickbooksonline/tips.md
* Closes [US3254](https://rally1.rallydev.com/#/144351344360d/detail/userstory/176219283092)
=> Updated auth instructions and existing tips about sandbox accounts

_posts/2017-12-04-ReleaseNotes-2.142.md, docs/guides/ground-2-cloud/who-is-this-for.md
* Added links
* Removed Dynamis
* Closes [DE551](https://rally1.rallydev.com/#/144351344360d/detail/defect/180778382148)
* Closes [US4279](https://rally1.rallydev.com/#/144351344360d/detail/userstory/180078871448)
=> Updated release notes links and removed Dynamics

_posts/2017-12-26-ReleaseNotes-2.145.md, _posts/2018-01-02-ReleaseNotes-2.146.md
* Closes [US5955](https://rally1.rallydev.com/#/144351344360d/detail/userstory/188143606400)
=> added rn for 2.146 and 145

_includes/nav.html
* Closes [US6669](https://rally1.rallydev.com/#/144351344360d/detail/userstory/189681563196?fdp=true)
=> Updated link to sign up for a trial

_posts/2018-01-15-ReleaseNotes-2.148.md
* Closes [6844](https://rally1.rallydev.com/#/144351344360d/detail/userstory/190606079940)
=> Release notes for 2.148 and Skellie release

docs/guides/account-user-mgmt/user-management.md, docs/guides/account-user-mgmt/user-managementAPI.md
* Closes [6843](https://rally1.rallydev.com/#/144351344360d/detail/userstory/190604962924)
=> updated Manage Users sections

docs/guides/account-user-mgmt/user-management.md, docs/guides/account-user-mgmt/user-managementAPI.md
Closes [US6843](https://rally1.rallydev.com/#/144351344360d/detail/userstory/190604962924)
=> making some final edits after review

_includes/Elements/netsuite/authenticate.md, _includes/Elements/netsuite/events2.md, _includes/Elements/netsuite/index.md, _includes/Elements/netsuite/setup.md
* Closes [US6645](https://rally1.rallydev.com/#/144351344360d/detail/userstory/189205650144)
=> Updated token-based name to custom where applicable

_posts/2018-01-28-ReleaseNotes-2.150.md
* Closes [US7258](https://rally1.rallydev.com/#/144351344360d/detail/userstory/192432878152)
=> added release notes

_includes/account-user/roles.md, _posts/2018-01-28-ReleaseNotes-2.150.md, _posts/2018-02-05-ReleaseNotes-2.151.md, docs/guides/elements/events.md
* Closes [US8086](https://rally1.rallydev.com/#/144351344360d/detail/userstory/195722660216)
=> Added release notes and fixed a few typos

_layouts/rn-item.html, _layouts/rn.html, _layouts/sidebarapidocs.html, _layouts/sidebarelementdoc.html, _layouts/sidebarelementtile.html, _layouts/sidebarleft.html, docs/home.md
=> updated canononical links to see if it works

Gemfile.lock, _layouts/default.html, _layouts/release-note-item.html, _layouts/rn-item.html, _layouts/rn.html, _layouts/sidebarapidocs.html, _layouts/sidebarelementdoc.html, _layouts/sidebarelementtile.html, _layouts/sidebarleft.html, docs/home.md
* Closes [US6727](https://rally1.rallydev.com/#/144351344360d/detail/userstory/190016730060)
=> Adding canonical links

docs/elements/hootsuite/events.md, docs/elements/infusionsoft-crm/index.md, docs/guides/common-resources/mappingapi.md, docs/guides/elements/auth.md, docs/guides/elements/custom-elements.md, docs/guides/elements/instances.md, docs/guides/formulasC2/build-template.md, docs/guides/formulasC2/examples.md, docs/guides/formulasC2/index.md, docs/guides/formulasC2/reference.md, docs/guides/formulasC2/referenceAPI.md, docs/guides/home.md, docs/platform-api/usage/api-documentation.md
* Closes [US6727](https://rally1.rallydev.com/#/144351344360d/detail/userstory/190016730060)
=> fixed redirects

_includes/Formulas/faar-status-codes.md, _posts/2018-02-12-ReleaseNotes-2.152.md, docs/guides/formulasC2/faar.md
* Closes [US8087](https://rally1.rallydev.com/#/144351344360d/detail/userstory/195722673324)
=> added release notes and updated FaaR docs

_layouts/rn.html, _posts/2018-02-26-ReleaseNotes-2.154.md
* Closes [US9032](https://rally1.rallydev.com/#/144351344360d/detail/userstory/199587592128)
=> Adding release notes for 2154

docs/elements/onedrive/onedrive-create-instance.md
*updated the onedrive docs to include information about converged apps
https://rally1.rallydev.com/#/144349237612d/detail/defect/199593670912
=> updated documentation with converged app info

_posts/2018-03-12-ReleaseNotes-2.156.md
=> Release notes and Freshbooks Cloud Accounting docs

_posts/2018-03-19-ReleaseNotes-2.158.md
* Closes [US10225](https://rally1.rallydev.com/#/144351344360d/detail/userstory/204650020428)
=> added rn for 2.158

docs/elements/salesforce/tips.md
* Closes [US9494](https://rally1.rallydev.com/#/144351344360d/detail/userstory/202779070816)
=> added tip about concurrency to sfdc

_posts/2018-04-03-ReleaseNotes-2.160.md
* Closes [#10225](https://rally1.rallydev.com/#/144349238268d/detail/userstory/204650020428)
=> Adding RN 2.160

_posts/2018-04-23-ReleaseNotes-2.163.md, docs/elements/maximizer/authenticate.md
=> release notes

_elementTemplate/index.md, docs/elements.md, docs/elements/sap-b-one/index.md
* Closes [Rally](https://rally1.rallydev.com/#/144351344360d/detail/userstory/197602923968)
=> sap b1 docs

_posts/2018-05-07-ReleaseNotes-2.165.md
* Closes [Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/218768938700)
=> adding release notes

docs/legacy/element-builder/element-builder-hooks.md
* changes code samples from using `return` to using `done()`
* Closes #DE2447
=> Change return to done

_includes/banner.html
* extends documentation expiration banner to 11/11
=> more time, soon to be expiring

_includes/banner.html
* updated the expiration banner to 12/14/2018
=> drop dead for docs migration

api-docs/api.js, api-docs/swagger.html
* The element API doc swagger will now always get the latest version
* Closes #idk
=> Added specification of swagger version in the /:elementId/docs call

.circleci/config.yml
=> Adding working directory for deploy
